eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka,http://localhost:2222/eureka
server:
  port: 15000

spring:
  application:
    name: mag-service
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create

